### ISSUE TITLE
Wrapper not caching

### ISSUE THREAD

**Issue by sebastienros** [ShadowDancer/RazorAssemblyCache#1]
Looking at this line https://github.com/ShadowDancer/RazorAssemblyCache/blob/master/src/RazorAssemblyCache/RazorAssemblyCacheProviderWrapper.cs#L19

It seems the `_cache` property is never assigned and you will return a new instance all the time. It doesn't look like it was the intent.

**Comment by ShadowDancer** [comment]
Thanks. 

I see that You already inspected this case of caching assemblies in Orchard project, so maybe you could share some insights with me, because AFAIK it will take you some time to make it right way (I guess until vs 2017?).

I see 3 issues with problem that I am trying to solve:

1. Cannot run on core framework because I need to load Assembly form bytestream (looks like I cannot solve that for now)
2. Cache is not invalidated when view is edited - my proposed solution is to check time stamp on cshtml and dll files, and recompile as required
3. Dependency of cached dll may change (let's say that newtonsoft.json is updated from 9.0.0 to 9.0.1) - then AFAIK (gotta test this) I will get TypeLoadException, so I will be able to discard type from cached 

assembly and invoke compiler again with DefaultCompilerCacheProvider
Is this right way to solve that? Do you know about any other major problems with such library?

**Comment by sebastienros** [comment]
For these reasons we decided to postpone this in Orchard and only support
precompiled views. @jtkech is the expert.

**Comment by jtkech** [comment]
Yes, we tried such a solution but as @sebastienros said we now use the razor views compilation tool.

We could just wrap the default roslyn compilation service but, because there is not yet an assembly builder method to create an assembly file from an assembly object, we needed to use a copy of it, this to use the same memory streams and then be able to create / update assembly files.

https://github.com/jtkech/Orchard2/blob/95d9891f16499b515dd5ba3954a8287b1e25bcfd/src/Microsoft.AspNetCore.Mvc.Modules.Hosting/Mvc/Razor/DefaultRoslynCompilationService.cs

And we register somewhere our custom class as a singleton service.

    services.AddSingleton<ICompilationService, DefaultRoslynCompilationService>();

We didn't use another class for caching, all is done in the compilation service which is naturally called on a first view rendering and if the *.cshtml file is updated when the app runs. So, here we can check the dates of the razor view and the cached assembly file.

Notice that to load the assembly from the cached file, we still do it through a memory stream. This way, the file is never used by the runtime, so you can update it when the view is modified.

About the above points.

1. Try to use.

        System.Runtime.Loader.AssemblyLoadContext.Default.LoadFromFile()

    But, as said above we always use.

        System.Runtime.Loader.AssemblyLoadContext.Default.LoadFromStream()

2. In our case, it was naturally done when the compiler service was recalled.

3. We analyze dependencies for our modules projects which are not part of the app and are dynamically compiled (if needed) and loaded at runtime. But this was not yet implemented for razor views and we decided to use the view compilation tool before doing it. So, when a dependency was updated we needed to delete the precompiled files.

    But seems not so easy to resolve dependencies from an assembly object. From our modules we use the dotnet project model when the project.json is there, or the dependency context but which only provides relative path, so we have to check the context (e.g if published), resolve the package storage ...

    So, never done from an assembly object. So the first idea i can give you on the fly is try to use the assembly.ExportedTypes, then for each one see its BaseType and from which assembly it is defined, and finally cache e.g the assembly name / version and / or its location and date ...

Best.

**Comment by ShadowDancer** [comment]
Thanks!

```We didn't use another class for caching, all is done in the compilation service which is naturally called on a first view rendering and if the *.cshtml file is updated when the app runs. So, here we can check the dates of the razor view and the cached assembly file.```
I use separate service for creating caches to avoid loading and parsing .cshtml file.
